# Generated by Django 4.2.7 on 2023-12-11 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_rename_desc_product_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="type",
            new_name="is_digital",
        ),
    ]
